# Generated by Django 3.2.3 on 2021-05-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_close', models.CharField(max_length=255)),
                ('side', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(max_length=255)),
                ('share_price', models.FloatField(max_length=255)),
                ('cost_basis', models.FloatField(max_length=255)),
                ('pnl', models.FloatField(max_length=255)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.date')),
            ],
        ),
    ]
