# Generated by Django 3.2.3 on 2021-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='cost_basis',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='share_price',
            field=models.FloatField(),
        ),
    ]
