# Generated by Django 3.2.3 on 2021-05-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20210527_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='DateTradePlace',
        ),
        migrations.RenameField(
            model_name='datetradeplace',
            old_name='date',
            new_name='date_placed',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='date',
            new_name='date_placed',
        ),
    ]
