# Generated by Django 3.2.3 on 2021-05-27 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20210527_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
