# Generated by Django 3.2.3 on 2021-05-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_trade_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateTradePlace',
            new_name='Date',
        ),
    ]
