# Generated by Django 3.2.3 on 2021-05-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_alter_trade_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
